name: portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.7
  provider: ^6.1.2
  go_router: ^14.6.2

  url_launcher: ^6.3.1

  #Animations
  flutter_portal: ^1.1.4
  animations: ^2.0.11
  motion: ^2.0.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Nohemi
      fonts:
        - asset: assets/fonts/Nohemi-Thin.otf
          weight: 100
        - asset: assets/fonts/Nohemi-Light.otf
          weight: 300
        - asset: assets/fonts/Nohemi-Regular.otf
          weight: 400
        - asset: assets/fonts/Nohemi-Medium.otf
          weight: 500
        - asset: assets/fonts/Nohemi-Bold.otf
          weight: 700
