name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # main branch'e push yapıldığında tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Kodunuzu alır

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Flutter ortamını kurar
        with:
          flutter-version: "3.27.0" # Stabil sürümü kullanır

      - name: Install Dependencies
        run: flutter pub get # Proje bağımlılıklarını indirir

      - name: Build Flutter Web
        run: flutter build web --release # Web için derleme yapar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Dağıtım işlemi
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }} # Otomatik token
          publish_dir: build/web # Derlenen dosyaların dizini
